/*
    This script checks that labels will be loaded by Mesen2.

    Why is this needed?
    The Mesen2 emulator can load labels from the `mtpo.dbg` file generated by ca65, and parse the source code for label comments.
    However there are strict requirements for this to work correctly, which are not written down anywhere.
    When a label isn't loaded, or the comment isn't available, it can be difficult to diagnose.
    This script helps check for problems.

    Usage:
    node helper_programs/check_labels.js

    When to run:
    To help fix known issues, or to help find unknown issues.
*/
import assert from 'assert';
import fs from 'fs';

/**
 * This function reads a dbg file and prints out any labels that are missing a segment.
 * This is useful for finding labels that will not be loaded from the dbg file into the Mesen2 emulator.
 */
function loadDbgInfo(data) {

    // Open the dbg file and split it into lines
    const lines = data.split('\n') // Get individual lines
        .filter(Boolean); // Remove empty lines
    
    const blocks = new Map();
    blocks.set("file", new Map())
    blocks.set("line", new Map())
    blocks.set("mod", new Map())
    blocks.set("seg", new Map())
    blocks.set("span", new Map())
    blocks.set("scope", new Map())
    blocks.set("sym", new Map())
    blocks.set("type", new Map())

    for (let i = 0; i < lines.length; i++) {
        /*
         * Split each line into a line type, and a list of fields.
         * Example lines:
         *   seg	id=4,name="ZEROPAGE",start=0x000000,size=0x0001,addrsize=zeropage,type=rw
         *   sym	id=26469,name="GenPtrE0",addrsize=zeropage,scope=13,def=19999,ref=18309,val=0xE0,seg=4,type=lab
         */
        const [dbgType, fieldList] = lines[i].split("\t");
        assert(dbgType, `Line ${i + 1} is missing type`);
        assert(fieldList, `Line ${i + 1} is missing fields`);

        const block = blocks.get(dbgType);
        if (block === undefined) {
            continue
        }

        /*
         * Split the field list into an object with key-value pairs.
         * Example:
         *  "seg=4,type=lab" => {seg: "4", type: "lab"}
         * 
         */
        const fields = new Map(fieldList.split(",").map(a => a.split("=")))

        // All records MUST have an ID
        const id = fields.get("id")
        if (id === undefined) {
            continue
        }

        assert.equal(block.has(id), false, "must not have dupicate IDs for the same type")
        block.set(id, fields)
    }

    return blocks;
}

function fetchSourceLabelComments(pathGlob) {
    const files = [
        "source_files/PRG_Bank000.asm",
        "source_files/PRG_Bank001.asm",
        "source_files/PRG_Bank002.asm",
        "source_files/PRG_Bank003.asm",
        "source_files/PRG_Bank004.asm",
        "source_files/PRG_Bank005.asm",
        "source_files/PRG_Bank006.asm",
        "source_files/PRG_Bank007.asm",
        "source_files/PRG_Bank008.asm",
        "source_files/PRG_Bank009.asm",
        "source_files/PRG_Bank00A.asm",
        "source_files/PRG_Bank00B.asm",
        "source_files/PRG_Bank00C.asm",
        "source_files/PRG_BankDEF.asm",
        "source_files/RAM.asm",
        "source_files/Mike_Tysons_Punchout_Defines.asm",
    ]
    const commentMap = new Map();
    for (const file of files) {
        const source = fs.readFileSync(file).toString().split("\n")
        for (const line of source) {
            const match = line.match(/^\s*(?<label>\w+)\s*:(.*;(?<comment>.+))?/)
            if (!match) continue;
            const {label, comment} = match.groups
            if (!commentMap.has(label)) {
                commentMap.set(label, comment || "")
            }
        }
    }
    return commentMap;
}

function checkMissingLabelComments(dbgInfo) {
    const symbols = dbgInfo.get("sym");
    assert(symbols !== undefined)
    const lines = dbgInfo.get("line");
    assert(lines !== undefined)
    const files = dbgInfo.get("file");
    assert(files !== undefined)

    const commentMap = fetchSourceLabelComments()
    // console.log("commentMap", commentMap);return;
    // console.log(commentMap.has("TriangleCntrl3")); return;

    const symbolCount = symbols.size;
    let symbolsPassed = 0;

    symbols.forEach(symFields => {
        if (symFields.get("type") !== "lab") {
            symbolsPassed++
            return
        }
        const label = symFields.get("name").replace(/^"(.*)"$/, "$1")
        if (label === undefined) {
            symbolsPassed++
            return
        }
        if (commentMap.has(label) && commentMap.get(label).trim().length == 0) {
            // No comment detected, so don't check if it is in the dbg file
            symbolsPassed++
            return;
        }
        if (symFields.get("seg") === undefined) {
            console.error(`Label "${label}" has no segment`)
            return
        }
        const lineID = symFields.get("def")
        if (lineID === undefined) {
            console.error(`Label "${label}" has no definition`)
            return
        }
        const line = lines.get(lineID)
        if (line === undefined) {
            console.error(`Label "${label}" could not find lineID ${lineID}`)
            return
        }
        const fileID = line.get("file")
        if (fileID === undefined) {
            if (fileID != 17) {
                symbolsPassed++;
                return
            }
            console.error(`Label "${label}" lineID ${lineID} has no file`)
            return
        }
        const spanID = line.get("span");
        if (spanID === undefined) {
            console.error(`Label "${label}" lineID ${lineID} has no span`)
            return
        }
        const file = files.get(fileID)
        if (fileID === undefined) {
            console.error(`Label "${label}" lineID ${lineID} could not find fileID ${fileID}`)
            return
        }
        symbolsPassed++;
    });
    const symbolErrorCount = symbolCount - symbolsPassed
    console.log(`Missing comments: ${symbolErrorCount}`)
}


// The dbg file is created by ca65 using the "--dbgfile" option. Run make to generate it.
const dbgInfo = loadDbgInfo(fs.readFileSync("output_files/mtpo.dbg", 'utf8'));
dbgInfo.forEach((records, dbgType) => {
    console.log(`${dbgType} => ${records.size}`)
});
checkMissingLabelComments(dbgInfo)